Mouse Sensitivity Dialog
SimBoi/WireframeRenderer pull request #1
Opened 2022-11-22 18:43 UTC by heebmohammad

2022-11-23 20:18 UTC, SimBoi commented on CGWork/CGWorkView.cpp
> +	double s = (val >= 0) ? val : (1.0 / val);
1.0 / -val

2022-11-23 20:22 UTC, SimBoi commented on CGWork/CGWorkView.cpp
> +	val = val * parentObject.rotation_sensitivity;
rotation_sensitivity should be a global variable in CGWorkView (not data variable in CG::Object), because the same sensitivity should be used for parentObject and children objects (for implementing advanced feature 1)

2022-11-23 20:22 UTC, SimBoi commented on CGWork/CGWorkView.cpp
> +	val = val * parentObject.rotation_sensitivity;
same with translation sensitivity and scale sensitivity

2022-11-23 20:24 UTC, SimBoi commented on CGWork/CGWorkView.cpp
> +	val = val % 360; // ??
doesnt really make a difference since sin(theta) is the same as sin(theta + k*2*pi)

2022-11-23 20:30 UTC, SimBoi commented on CGWork/CG_Object.h
> +		int translation_sensitivity, rotation_sensitivity, scale_sensitivity;
should be global variables in CGWorkView

2022-11-23 20:33 UTC, SimBoi commented on CGWork/iritSkel.cpp
> +	parentObject.setDefaultSensitivity();
this gets called once for every child object in the irit file, should move this call to either the initialized check in OnDraw  or to CGSkelProcessIritDataFiles function which only gets called once for every irit file

2022-11-23 20:34 UTC, SimBoi requested changes
added comments on lines that need to be changed

2022-11-23 21:16 UTC, heebmohammad commented on CGWork/CGWorkView.cpp
> +	val = val * parentObject.rotation_sensitivity;
we can access these values, right?

2022-11-24 12:44 UTC, SimBoi approved these changes

2022-11-24 12:44 UTC, merged

2022-11-24 12:52 UTC, SimBoi commented
found a bug when clicking on one of the axis buttons, the the previously selected axis doesnt get deselected